[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#4FBDE2"
backgroundColor = "#080C16"
secondaryBackgroundColor = "#0F1729"
textColor = "#E2E8F0"
font = "sans serif"
